"""
app/utils/script_generator/health_impact.py
===========================================
Generates a standalone, runnable Python example script for the Health Impact
tab. The script reproduces threat-zone generation + health-threshold overlays
and saves an interactive Folium map.
"""

from __future__ import annotations

import textwrap
from datetime import datetime

from .threat_zones import _slug, _single_source_block, _multi_source_block


def generate_health_impact_script(
    *,
    chemical: str,
    molecular_weight: float,
    release_type: str,
    source_term_mode: str,
    lat: float,
    lon: float,
    release_rate: float,
    tank_height: float,
    duration_minutes: float,
    mass_released_kg: float,
    terrain_roughness: str,
    receptor_height_m: float,
    weather_mode: str,
    wind_speed: float,
    wind_dir: float,
    temperature_c: float,
    humidity_pct: float,
    cloud_cover_pct: float,
    timezone_offset_hrs: float,
    datetime_mode: str,
    specific_datetime: str | None,
    aegl_thresholds: dict,
    x_max: int,
    y_max: int,
    selected_threshold_sets: list[str],
    multi_sources: list[dict] | None = None,
) -> str:
    """Return standalone script text for Health Impact analysis."""

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    chem_slug = _slug(chemical)
    rel_type_label = "Multi-Source" if release_type == "multi" else "Single Source"

    if weather_mode == "auto":
        weather_block = textwrap.dedent("""\
            weather = get_weather(
                latitude=SOURCE_LAT,
                longitude=SOURCE_LON,
                source="open_meteo",
            )
        """)
    else:
        weather_block = textwrap.dedent("""\
            weather = {
                "wind_speed"    : WIND_SPEED,
                "wind_dir"      : WIND_DIRECTION,
                "temperature_K" : TEMPERATURE_C + 273.15,
                "humidity"      : HUMIDITY / 100.0,
                "cloud_cover"   : CLOUD_COVER / 100.0,
                "source"        : "manual",
            }
        """)

    if datetime_mode == "specific" and specific_datetime:
        dt_block = f'simulation_datetime = datetime.fromisoformat("{specific_datetime}")'
    else:
        dt_block = "simulation_datetime = datetime.now()"

    if release_type == "single":
        dispersion_block = _single_source_block(source_term_mode)
    else:
        dispersion_block = _multi_source_block(source_term_mode, multi_sources or [])

    if release_type == "multi" and multi_sources:
        lines = ["RELEASE_SOURCES = ["]
        for i, src in enumerate(multi_sources):
            lines.append(f"    {{  # Source {i + 1}")
            lines.append(f'        "lat"   : {src["lat"]},')
            lines.append(f'        "lon"   : {src["lon"]},')
            lines.append(f'        "name"  : "{src.get("name", f"Source {i + 1}")}",')
            lines.append(f'        "height": {src["height"]},')
            lines.append(f'        "rate"  : {src["rate"]},')
            lines.append("    },")
        lines.append("]")
        multi_source_cfg = "\n".join(lines)
    else:
        multi_source_cfg = "# No additional sources (single-source mode)"

    weather_import = (
        "from pyeldqm.core.meteorology.realtime_weather import get_weather"
        if weather_mode == "auto"
        else "# from pyeldqm.core.meteorology.realtime_weather import get_weather"
    )

    selected_sets_repr = repr(selected_threshold_sets or ["aegl"])

    def _d(s: str) -> str:
        return textwrap.dedent(s).lstrip("\n")

    s_doc = _d(f"""\
        \"\"\"
        Health Impact Analysis — Auto-Generated Example
        ===============================================
        Generated by pyELDQM Dash app on {now_str}

        Scenario   : {rel_type_label} Release
        Chemical   : {chemical}
        Location   : {lat}, {lon}

        Run from any directory:
            python {chem_slug}_health_impact.py

        Outputs saved to ./outputs/health_impact/
        - {chem_slug}_health_impact_map_<ts>.html
        \"\"\"
    """)

    s_imports = _d(f"""\
        from pathlib import Path
        from datetime import datetime
        import webbrowser
        import numpy as np
        import folium
        from shapely.geometry import mapping as geom_mapping

        from pyeldqm.core.dispersion_models.gaussian_model import (
            calculate_gaussian_dispersion,
            multi_source_concentration,
        )
        from pyeldqm.core.meteorology.stability import get_stability_class
        from pyeldqm.core.meteorology.wind_profile import wind_speed as wind_profile
        {weather_import}
        from pyeldqm.core.utils.features import setup_computational_grid
        from pyeldqm.core.utils.zone_extraction import extract_zones
        from pyeldqm.core.health_thresholds import (
            get_aegl_thresholds,
            get_erpg_thresholds,
            get_pac_thresholds,
            get_idlh_threshold,
        )
    """)

    s_cfg = _d(f"""\
        CHEMICAL_NAME       = {chemical!r}
        MOLECULAR_WEIGHT    = {molecular_weight}
        SOURCE_LAT          = {lat}
        SOURCE_LON          = {lon}
        TIMEZONE_OFFSET_HRS = {timezone_offset_hrs}

        RELEASE_TYPE        = {release_type!r}
        SOURCE_TERM_MODE    = {source_term_mode!r}
        RELEASE_RATE        = {release_rate}
        TANK_HEIGHT         = {tank_height}
        DURATION_MINUTES    = {duration_minutes}
        MASS_RELEASED_KG    = {mass_released_kg}
        TERRAIN_ROUGHNESS   = {terrain_roughness!r}
        RECEPTOR_HEIGHT_M   = {receptor_height_m}

        WEATHER_MODE        = {weather_mode!r}
        WIND_SPEED          = {wind_speed}
        WIND_DIRECTION      = {wind_dir}
        TEMPERATURE_C       = {temperature_c}
        HUMIDITY            = {humidity_pct}
        CLOUD_COVER         = {cloud_cover_pct}

        AEGL_THRESHOLDS = {aegl_thresholds}
        X_MAX = {x_max}
        Y_MAX = {y_max}
        SELECTED_SETS = {selected_sets_repr}

        {multi_source_cfg}
    """)

    s_main = _d(f"""\
        _THRESHOLD_COLORS = {{
            "AEGL-1": "#FFFF66", "AEGL-2": "#FFB84D", "AEGL-3": "#FF6666",
            "ERPG-1": "#ADD8E6", "ERPG-2": "#5599FF", "ERPG-3": "#CC77CC",
            "PAC-1": "#90EE90", "PAC-2": "#33BB66", "PAC-3": "#2D8A5E",
            "IDLH": "#CC3333",
        }}

        print("Running Health Impact analysis...")
        {dt_block}
        print(f"Simulation datetime: {{simulation_datetime.isoformat()}}")

        {weather_block}

        stability_class = get_stability_class(
            wind_speed=weather["wind_speed"],
            cloud_cover=weather["cloud_cover"],
            daytime=6 <= simulation_datetime.hour <= 18,
            urban=(TERRAIN_ROUGHNESS.upper() == "URBAN"),
        )

        u_ref = wind_profile(
            weather["wind_speed"],
            z=TANK_HEIGHT,
            z_ref=10,
            p=0.33 if TERRAIN_ROUGHNESS.upper() == "URBAN" else 0.15,
        )

        X, Y, _, _ = setup_computational_grid(
            x_max=X_MAX, y_max=Y_MAX, source_height=TANK_HEIGHT,
            source_lat=SOURCE_LAT, source_lon=SOURCE_LON,
            wind_direction=weather["wind_dir"],
        )

        RELEASE_DURATION_S = DURATION_MINUTES * 60.0
        TOTAL_MASS_G = MASS_RELEASED_KG * 1000.0

        {dispersion_block}

        all_thresholds = {{}}
        if "aegl" in SELECTED_SETS:
            try:
                all_thresholds.update(get_aegl_thresholds(CHEMICAL_NAME) or {{}})
            except Exception:
                pass
        if "erpg" in SELECTED_SETS:
            try:
                all_thresholds.update(get_erpg_thresholds(CHEMICAL_NAME) or {{}})
            except Exception:
                pass
        if "pac" in SELECTED_SETS:
            try:
                all_thresholds.update(get_pac_thresholds(CHEMICAL_NAME) or {{}})
            except Exception:
                pass
        if "idlh" in SELECTED_SETS:
            try:
                _idlh = get_idlh_threshold(CHEMICAL_NAME)
                if _idlh is not None:
                    all_thresholds["IDLH"] = float(_idlh)
            except Exception:
                pass

        all_zones = {{}}
        for threshold_name, threshold_value in all_thresholds.items():
            try:
                _thr = float(threshold_value)
            except Exception:
                continue
            zones = extract_zones(
                X, Y, concentration,
                {{threshold_name: _thr}},
                SOURCE_LAT, SOURCE_LON,
                wind_dir=weather["wind_dir"],
            )
            all_zones.update(zones)

        m = folium.Map(location=[SOURCE_LAT, SOURCE_LON], zoom_start=13, tiles="OpenStreetMap")
        folium.TileLayer(
            tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{{z}}/{{y}}/{{x}}",
            attr="Esri", name="Satellite", overlay=False, control=True,
        ).add_to(m)
        folium.Marker([SOURCE_LAT, SOURCE_LON], tooltip="Release Source",
                      icon=folium.Icon(color="red", icon="warning-sign")).add_to(m)

        for zone_name, zone_poly in all_zones.items():
            if zone_poly is None:
                continue
            color = _THRESHOLD_COLORS.get(zone_name, "#888888")
            folium.GeoJson(
                {{"type": "Feature", "geometry": geom_mapping(zone_poly), "properties": {{}}}},
                style_function=lambda _, c=color: {{
                    "fillColor": c, "color": c, "weight": 2, "fillOpacity": 0.3,
                }},
                tooltip=zone_name,
                name=zone_name,
            ).add_to(m)

        folium.LayerControl().add_to(m)

        _out_dir = Path.cwd() / "outputs" / "health_impact"
        _out_dir.mkdir(parents=True, exist_ok=True)
        _ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        _map_path = _out_dir / f"{chem_slug}_health_impact_map_{{_ts}}.html"
        m.save(str(_map_path))

        print(f"Map saved to: {{_map_path}}")
        print(f"Stability class: {{stability_class}}")
        print(f"Zones generated: {{len(all_zones)}}")
        webbrowser.open(_map_path.as_uri())
    """)

    return s_doc + "\n" + s_imports + "\n" + s_cfg + "\n" + s_main
