"""
app/utils/script_generator/shelter_analysis.py
==============================================
Generates a standalone, runnable Python example script for the Shelter
Analysis tab. The script reproduces threat-zone generation + shelter action
analysis and saves an interactive Folium map.
"""

from __future__ import annotations

import textwrap
from datetime import datetime

from .threat_zones import _slug, _single_source_block, _multi_source_block


def generate_shelter_script(
    *,
    chemical: str,
    molecular_weight: float,
    release_type: str,
    source_term_mode: str,
    lat: float,
    lon: float,
    release_rate: float,
    tank_height: float,
    duration_minutes: float,
    mass_released_kg: float,
    terrain_roughness: str,
    receptor_height_m: float,
    weather_mode: str,
    wind_speed: float,
    wind_dir: float,
    temperature_c: float,
    humidity_pct: float,
    cloud_cover_pct: float,
    timezone_offset_hrs: float,
    datetime_mode: str,
    specific_datetime: str | None,
    aegl_thresholds: dict,
    x_max: int,
    y_max: int,
    building_type: str,
    sheltering_time_min: float,
    evacuation_time_min: float,
    sample_grid_points: int,
    multi_sources: list[dict] | None = None,
) -> str:
    """Return standalone script text for Shelter analysis."""

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    chem_slug = _slug(chemical)
    rel_type_label = "Multi-Source" if release_type == "multi" else "Single Source"

    if weather_mode == "auto":
        weather_block = textwrap.dedent("""\
            weather = get_weather(
                latitude=SOURCE_LAT,
                longitude=SOURCE_LON,
                source="open_meteo",
            )
        """)
    else:
        weather_block = textwrap.dedent("""\
            weather = {
                "wind_speed"    : WIND_SPEED,
                "wind_dir"      : WIND_DIRECTION,
                "temperature_K" : TEMPERATURE_C + 273.15,
                "humidity"      : HUMIDITY / 100.0,
                "cloud_cover"   : CLOUD_COVER / 100.0,
                "source"        : "manual",
            }
        """)

    if datetime_mode == "specific" and specific_datetime:
        dt_block = f'simulation_datetime = datetime.fromisoformat("{specific_datetime}")'
    else:
        dt_block = "simulation_datetime = datetime.now()"

    if release_type == "single":
        dispersion_block = _single_source_block(source_term_mode)
    else:
        dispersion_block = _multi_source_block(source_term_mode, multi_sources or [])

    if release_type == "multi" and multi_sources:
        lines = ["RELEASE_SOURCES = ["]
        for i, src in enumerate(multi_sources):
            lines.append(f"    {{  # Source {i + 1}")
            lines.append(f'        "lat"   : {src["lat"]},')
            lines.append(f'        "lon"   : {src["lon"]},')
            lines.append(f'        "name"  : "{src.get("name", f"Source {i + 1}")}",')
            lines.append(f'        "height": {src["height"]},')
            lines.append(f'        "rate"  : {src["rate"]},')
            lines.append("    },")
        lines.append("]")
        multi_source_cfg = "\n".join(lines)
    else:
        multi_source_cfg = "# No additional sources (single-source mode)"

    weather_import = (
        "from pyeldqm.core.meteorology.realtime_weather import get_weather"
        if weather_mode == "auto"
        else "# from pyeldqm.core.meteorology.realtime_weather import get_weather"
    )

    def _d(s: str) -> str:
        return textwrap.dedent(s).lstrip("\n")

    # ── Docstring ───────────────────────────────────────────────────────────
    s_doc = _d(f"""\
        \"\"\"
        Shelter Analysis — Auto-Generated Example
        =========================================
        Generated by pyELDQM Dash app on {now_str}

        Scenario   : {rel_type_label} Release
        Chemical   : {chemical}
        Location   : {lat}, {lon}

        Run from any directory:
            python {chem_slug}_shelter_analysis.py

        Outputs saved to ./outputs/shelter_analysis/
        - {chem_slug}_shelter_map_<ts>.html
        \"\"\"
    """)

    # ── Imports ─────────────────────────────────────────────────────────────
    s_imports = _d(f"""\
        from pathlib import Path
        from datetime import datetime
        import webbrowser
        import numpy as np
        import folium
        from shapely.geometry import mapping as geom_mapping

        from pyeldqm.core.dispersion_models.gaussian_model import (
            calculate_gaussian_dispersion,
            multi_source_concentration,
        )
        from pyeldqm.core.meteorology.stability import get_stability_class
        from pyeldqm.core.meteorology.wind_profile import wind_speed as wind_profile
        {weather_import}
        from pyeldqm.core.utils.features import setup_computational_grid
        from pyeldqm.core.utils.zone_extraction import extract_zones
        from pyeldqm.core.protective_actions import analyze_shelter_zones
    """)

    # ── Configuration constants (no multi-line vars embedded) ───────────────
    s_cfg = _d(f"""\
        CHEMICAL_NAME       = {chemical!r}
        MOLECULAR_WEIGHT    = {molecular_weight}
        SOURCE_LAT          = {lat}
        SOURCE_LON          = {lon}
        TIMEZONE_OFFSET_HRS = {timezone_offset_hrs}

        RELEASE_TYPE        = {release_type!r}
        SOURCE_TERM_MODE    = {source_term_mode!r}
        RELEASE_RATE        = {release_rate}
        TANK_HEIGHT         = {tank_height}
        DURATION_MINUTES    = {duration_minutes}
        MASS_RELEASED_KG    = {mass_released_kg}
        TERRAIN_ROUGHNESS   = {terrain_roughness!r}
        RECEPTOR_HEIGHT_M   = {receptor_height_m}

        WEATHER_MODE        = {weather_mode!r}
        WIND_SPEED          = {wind_speed}
        WIND_DIRECTION      = {wind_dir}
        TEMPERATURE_C       = {temperature_c}
        HUMIDITY            = {humidity_pct}
        CLOUD_COVER         = {cloud_cover_pct}

        AEGL_THRESHOLDS = {aegl_thresholds}
        X_MAX = {x_max}
        Y_MAX = {y_max}
        NX    = 500
        NY    = 500

        BUILDING_TYPE = {building_type!r}
        SHELTERING_TIME_MIN = {sheltering_time_min}
        EVACUATION_TIME_MIN = {evacuation_time_min}
        SAMPLE_GRID_POINTS = {sample_grid_points}
    """)

    # ── Main body part 1: start → datetime ──────────────────────────────────
    s_main_1 = _d(f"""\
        print("Running Shelter Analysis...")
        {dt_block}
        print(f"Simulation datetime: {{simulation_datetime.isoformat()}}")
    """)

    # ── Main body part 2: stability → grid → release constants ──────────────
    s_main_2 = _d("""\
        stability_class = get_stability_class(
            wind_speed=weather["wind_speed"],
            datetime_obj=simulation_datetime,
            latitude=SOURCE_LAT,
            longitude=SOURCE_LON,
            cloudiness_index=weather.get("cloud_cover", 0) * 10,
            timezone_offset_hrs=TIMEZONE_OFFSET_HRS,
        )
        print(f"  Stability class : {stability_class}")

        u_ref = wind_profile(
            z_user=TANK_HEIGHT,
            z0=3.0,
            U_user=weather["wind_speed"],
            stability_class=stability_class,
        )

        X, Y, _, _ = setup_computational_grid(
            x_max=X_MAX, y_max=Y_MAX, nx=NX, ny=NY,
        )

        RELEASE_DURATION_S = DURATION_MINUTES * 60.0
        TOTAL_MASS_G = MASS_RELEASED_KG * 1000.0
    """)

    # ── Main body part 3: zones → shelter analysis → map → output ───────────
    s_main_3 = _d(f"""\
        threat_zones = extract_zones(
            X, Y, concentration, AEGL_THRESHOLDS,
            SOURCE_LAT, SOURCE_LON,
            wind_dir=weather["wind_dir"],
        )

        shelter_result = analyze_shelter_zones(
            threat_zones=threat_zones,
            source_lat=SOURCE_LAT,
            source_lon=SOURCE_LON,
            building_type=BUILDING_TYPE,
            sheltering_time_minutes=SHELTERING_TIME_MIN,
            evacuation_time_minutes=EVACUATION_TIME_MIN,
            grid_points=SAMPLE_GRID_POINTS,
        )

        shelter_zones = []
        evacuate_zones = []
        total_sampled = 0
        total_shelter = 0
        total_evacuate = 0

        for zone_name, zone_info in shelter_result.items():
            poly = threat_zones.get(zone_name)
            entry = {{"name": zone_name, "polygon": poly}}
            rec = zone_info.get("primary_recommendation", "SHELTER")
            total_sampled += zone_info.get("total_samples", 0)
            total_shelter += zone_info.get("shelter_count", 0)
            total_evacuate += zone_info.get("evacuate_count", 0)
            if rec == "EVACUATE":
                evacuate_zones.append(entry)
            else:
                shelter_zones.append(entry)

        overall_primary = "EVACUATE" if total_evacuate > total_shelter else "SHELTER IN PLACE"

        m = folium.Map(location=[SOURCE_LAT, SOURCE_LON], zoom_start=13, tiles="OpenStreetMap")
        folium.TileLayer(
            tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{{z}}/{{y}}/{{x}}",
            attr="Esri", name="Satellite", overlay=False, control=True,
        ).add_to(m)
        folium.Marker([SOURCE_LAT, SOURCE_LON], tooltip="Release Source",
                      icon=folium.Icon(color="red", icon="warning-sign")).add_to(m)

        for zname, zpoly in threat_zones.items():
            if zpoly is None:
                continue
            folium.GeoJson(
                {{"type": "Feature", "geometry": geom_mapping(zpoly), "properties": {{}}}},
                style_function=lambda _: {{
                    "fillColor": "#66a3ff", "color": "#2f5fb3", "weight": 1.5, "fillOpacity": 0.18,
                }},
                tooltip=zname,
                name=zname,
            ).add_to(m)

        for zone in shelter_zones:
            poly = zone.get("polygon")
            if poly is None:
                continue
            folium.GeoJson(
                {{"type": "Feature", "geometry": geom_mapping(poly), "properties": {{}}}},
                style_function=lambda _: {{
                    "fillColor": "#90EE90", "color": "#228B22", "weight": 2, "fillOpacity": 0.35,
                }},
                tooltip=f"{{zone.get('name', 'Zone')}}: SHELTER",
                name="Shelter-in-Place Zones",
            ).add_to(m)

        for zone in evacuate_zones:
            poly = zone.get("polygon")
            if poly is None:
                continue
            folium.GeoJson(
                {{"type": "Feature", "geometry": geom_mapping(poly), "properties": {{}}}},
                style_function=lambda _: {{
                    "fillColor": "#FF6347", "color": "#B22222", "weight": 2, "fillOpacity": 0.35,
                }},
                tooltip=f"{{zone.get('name', 'Zone')}}: EVACUATE",
                name="Evacuation Zones",
            ).add_to(m)

        folium.LayerControl().add_to(m)

        _out_dir = Path.cwd() / "outputs" / "shelter_analysis"
        _out_dir.mkdir(parents=True, exist_ok=True)
        _ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        _map_path = _out_dir / f"{chem_slug}_shelter_map_{{_ts}}.html"
        m.save(str(_map_path))

        print(f"Map saved to: {{_map_path}}")
        print(f"Primary recommendation: {{overall_primary}}")
        print(f"Sampled points: {{total_sampled}}")
        webbrowser.open(_map_path.as_uri())
    """)

    # Assemble: multi-line vars concatenated directly, never embedded inside
    # a _d() f-string — same pattern as threat_zones.py.
    return (
        s_doc
        + "\n" + s_imports
        + "\n" + s_cfg
        + "\n" + multi_source_cfg + "\n"
        + "\n" + s_main_1
        + "\n" + weather_block
        + "\n" + s_main_2
        + "\n" + dispersion_block
        + "\n" + s_main_3
    )
