"""
Chemical Threat Zones Calculation — Auto-Generated Example
===========================================================
Generated by pyELDQM Dash app on 2026-02-23 10:17:36

Scenario   : Single Source Release
Chemical   : AMMONIA
Location   : 31.6911, 74.0822
Weather    : Manual

This script is a complete, self-contained reproduction of the threat-zone
calculation that was performed inside the pyELDQM Dash application,
including all outputs: chemical properties, simulation conditions, zone
distances, interactive map, and 5 analytics charts.
Run it directly from the ``examples/`` directory:

    python ammonia_threat_zones.py

Outputs (saved to outputs/threat_zones/)
-----------------------------------------
- ammonia_threat_zones_<ts>.html         — interactive Folium map
- ammonia_analytics_centerline_<ts>.html — centerline concentration profile
- ammonia_analytics_crosswind_<ts>.html  — crosswind concentration profiles
- ammonia_analytics_contour_<ts>.html    — 2D spatial concentration map
- ammonia_analytics_statistics_<ts>.html — concentration statistics & impact area
- ammonia_analytics_distance_<ts>.html   — max concentration vs distance

Dependencies
------------
    pip install numpy folium scikit-image branca requests plotly shapely

Notes
-----
- Adjust the configuration constants under CONFIGURATION to explore scenarios.
"""

# ============================================================================
# IMPORTS
# ============================================================================

import sys
import os
import webbrowser
from math import radians, cos, sin, asin, sqrt
from pathlib import Path
from datetime import datetime

import numpy as np

# -- Add project root to Python path ----------------------------------------
_here = os.path.dirname(os.path.abspath(__file__))
_root = os.path.dirname(_here)
if _root not in sys.path:
    sys.path.insert(0, _root)

# -- pyELDQM core imports ----------------------------------------------------
from core.dispersion_models.gaussian_model import (
    calculate_gaussian_dispersion,
    multi_source_concentration,
)
from core.meteorology.stability import get_stability_class
from core.meteorology.wind_profile import wind_speed as wind_profile
from core.chemical_database import ChemicalDatabase
# from core.meteorology.realtime_weather import get_weather  # not needed for manual weather
from core.visualization.folium_maps import (
    create_dispersion_map,
    meters_to_latlon,
    add_facility_markers,
    calculate_optimal_zoom_level,
)
from core.visualization import (
    add_zone_polygons,
    ensure_layer_control,
    fit_map_to_polygons,
)
from core.utils.features import setup_computational_grid
from core.utils.zone_extraction import extract_zones
from app.utils.plot_builders import (
    create_centerline_concentration_plot,
    create_crosswind_concentration_plot,
    create_concentration_contour_plot,
    create_concentration_statistics,
    create_distance_vs_concentration_plot,
)

# ============================================================================
# CONFIGURATION
# ============================================================================

# -- Chemical ----------------------------------------------------------------
CHEMICAL_NAME      = 'AMMONIA'
MOLECULAR_WEIGHT   = 17.03          # g/mol

# -- Release location --------------------------------------------------------
SOURCE_LAT         = 31.6911
SOURCE_LON         = 74.0822
TIMEZONE_OFFSET_HRS = 5.0

# -- Release parameters ------------------------------------------------------
RELEASE_TYPE       = 'single'            # "single" or "multi"
SOURCE_TERM_MODE   = 'continuous'        # "continuous" or "instantaneous"
RELEASE_RATE       = 800.0              # g/s  (continuous mode)
TANK_HEIGHT        = 3.0               # m above ground
DURATION_MINUTES   = 30.0          # release duration
MASS_RELEASED_KG   = 500.0          # total mass (instantaneous mode)
TERRAIN_ROUGHNESS  = 'URBAN'       # "URBAN" or "RURAL"
RECEPTOR_HEIGHT_M  = 1.5         # breathing-zone height (m)

# -- Weather (used only when WEATHER_MODE == "manual") -----------------------
WEATHER_MODE       = 'manual'            # "manual" or "auto"
WIND_SPEED         = 2.5                # m/s
WIND_DIRECTION     = 90.0                  # degrees (0=N, 90=E, 180=S, 270=W)
TEMPERATURE_C      = 25.0             # degrees C
HUMIDITY           = 65.0              # %
CLOUD_COVER        = 30.0           # %

# -- AEGL hazard thresholds (ppm) --------------------------------------------
AEGL_THRESHOLDS = {
    "AEGL-1": 30.0,     # Mild / noticeable effects
    "AEGL-2": 160.0,    # Irreversible effects
    "AEGL-3": 1100.0,   # Life-threatening
}

# -- Computational grid ------------------------------------------------------
X_MAX = 12000     # m  (downwind extent)
Y_MAX = 4000     # m  (crosswind extent)
NX    = 500
NY    = 500

# -- Multi-source definitions (used only when RELEASE_TYPE == 'multi') --
# No additional sources (single-source mode)

# ============================================================================
# CHEMICAL PROPERTIES
# ============================================================================
print("=" * 60)
print("CHEMICAL PROPERTIES")
print("=" * 60)
try:
    _db = ChemicalDatabase()
    _chem_data = next(
        (c for c in _db.get_all_chemicals() if c.get("name") == CHEMICAL_NAME),
        None,
    )
    if _chem_data:
        _prop_fields = [
            ("Name",                "name"),
            ("Molecular Weight",    "molecular_weight"),
            ("Boiling Point (K)",   "boiling_point_K"),
            ("Density (kg/m3)",     "density_kgm3"),
            ("Vapor Pressure (kPa)","vapor_pressure_kPa"),
            ("IDLH (ppm)",          "idlh_ppm"),
            ("LC50 (ppm)",          "lc50_ppm"),
            ("AEGL-1 (60 min)",     "aegl1_60min"),
            ("AEGL-2 (60 min)",     "aegl2_60min"),
            ("AEGL-3 (60 min)",     "aegl3_60min"),
            ("ERPG-1",              "erpg1"),
            ("ERPG-2",              "erpg2"),
            ("ERPG-3",              "erpg3"),
        ]
        for label, key in _prop_fields:
            val = _chem_data.get(key)
            if val is not None and val != "" and val != 0:
                print(f"  {label:<28}: {val}")
    else:
        print(f"  Molecular Weight : {MOLECULAR_WEIGHT} g/mol")
        print(f"  (Full database record not found for '{CHEMICAL_NAME}')")
except Exception as _e:
    print(f"  Molecular Weight : {MOLECULAR_WEIGHT} g/mol")
    print(f"  (Could not query database: {_e})")
print()

# ============================================================================
# SIMULATION DATETIME
# ============================================================================
simulation_datetime = datetime.now()
print(f"Simulation datetime : {simulation_datetime}")

# ============================================================================
# WEATHER CONDITIONS
# ============================================================================
print("\nFetching / setting weather conditions ...")

# Manual weather conditions (as entered in the app)
weather = {
    "wind_speed"    : WIND_SPEED,
    "wind_dir"      : WIND_DIRECTION,
    "temperature_K" : TEMPERATURE_C + 273.15,
    "humidity"      : HUMIDITY / 100.0,
    "cloud_cover"   : CLOUD_COVER / 100.0,
    "source"        : "manual",
}


# ============================================================================
# STABILITY CLASS
# ============================================================================
stability_class = get_stability_class(
    wind_speed=weather["wind_speed"],
    datetime_obj=simulation_datetime,
    latitude=SOURCE_LAT,
    longitude=SOURCE_LON,
    cloudiness_index=weather.get("cloud_cover", 0) * 10,
    timezone_offset_hrs=TIMEZONE_OFFSET_HRS,
)
print(f"  Stability class    : {stability_class}")

# ============================================================================
# COMPUTATIONAL GRID
# ============================================================================
print("\nSetting up computational grid ...")
X, Y, _, _ = setup_computational_grid(
    x_max=X_MAX, y_max=Y_MAX, nx=NX, ny=NY,
)
print(f"  Grid: {NX}x{NY} cells, downwind {X_MAX} m, crosswind {Y_MAX} m")

# ============================================================================
# DISPERSION CALCULATION
# ============================================================================
print("\nRunning Gaussian dispersion model ...")

RELEASE_DURATION_S = DURATION_MINUTES * 60.0
TOTAL_MASS_G       = MASS_RELEASED_KG * 1000.0

source_q       = RELEASE_RATE           # continuous release rate (g/s)
dispersion_mode = "continuous"

concentration, U_local, stability_class, resolved_sources = calculate_gaussian_dispersion(
    weather=weather, X=X, Y=Y,
    source_lat=SOURCE_LAT, source_lon=SOURCE_LON,
    molecular_weight=MOLECULAR_WEIGHT,
    default_release_rate=source_q,
    default_height=TANK_HEIGHT,
    z_ref=3.0, z_measurement=RECEPTOR_HEIGHT_M,
    t=RELEASE_DURATION_S, t_r=RELEASE_DURATION_S,
    mode=dispersion_mode,
    sources=[{
        "lat": SOURCE_LAT, "lon": SOURCE_LON,
        "name": "Release Source",
        "height": TANK_HEIGHT, "rate": source_q,
        "color": "red",
    }],
    latitude=SOURCE_LAT, longitude=SOURCE_LON,
    timezone_offset_hrs=TIMEZONE_OFFSET_HRS,
    roughness=TERRAIN_ROUGHNESS,
    datetime_obj=simulation_datetime,
)
print(f"  U_local         : {U_local:.2f} m/s")
print(f"  Stability class : {stability_class}")


# ============================================================================
# ZONE EXTRACTION
# ============================================================================
print("\nExtracting threat zones ...")
# Returns Dict[str, Optional[Polygon]]  (shapely Polygon or None per level)
threat_zones = extract_zones(
    X, Y, concentration, AEGL_THRESHOLDS,
    SOURCE_LAT, SOURCE_LON,
    wind_dir=weather["wind_dir"],
)

# ============================================================================
# SIMULATION CONDITIONS SUMMARY
# ============================================================================
print()
print("=" * 60)
print("METEOROLOGICAL CONDITIONS")
print("=" * 60)
_temp_c = weather.get("temperature_K", 273.15) - 273.15
_meteo_rows = [
    ("Wind Speed",      f"{weather.get('wind_speed', 0):.2f} m/s"),
    ("Wind Direction",  f"{weather.get('wind_dir', 0):.0f} deg"),
    ("Temperature",     f"{_temp_c:.1f} C"),
    ("Humidity",        f"{weather.get('humidity', 0)*100:.0f} %"),
    ("Cloud Cover",     f"{weather.get('cloud_cover', 0)*100:.0f} %"),
    ("Stability Class", stability_class),
    ("Weather Source",  weather.get("source", "unknown").title()),
]
for label, val in _meteo_rows:
    print(f"  {label:<22}: {val}")

print()
print("=" * 60)
print("RELEASE PARAMETERS")
print("=" * 60)
_src_mode_label = "Instantaneous/Puff" if SOURCE_TERM_MODE == "instantaneous" else "Continuous"
_release_rows = [
    ("Chemical",          CHEMICAL_NAME),
    ("Release Type",      RELEASE_TYPE.title()),
    ("Source Term Mode",  _src_mode_label),
    ("Release Rate",      f"{RELEASE_RATE} g/s"),
    ("Source Height",     f"{TANK_HEIGHT} m"),
    ("Duration",          f"{DURATION_MINUTES:.1f} min"),
    ("Mass Released",     f"{MASS_RELEASED_KG:.1f} kg"),
    ("Terrain Roughness", TERRAIN_ROUGHNESS),
    ("Receptor Height",   f"{RECEPTOR_HEIGHT_M:.1f} m"),
    ("Simulation Time",   str(simulation_datetime)),
]
for label, val in _release_rows:
    print(f"  {label:<22}: {val}")
print()

# ============================================================================
# ZONE DISTANCES FROM SOURCE
# ============================================================================

def _haversine_km(lat1, lon1, lat2, lon2):
    """Great-circle distance in km."""
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    dlon, dlat = lon2 - lon1, lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    return 2 * asin(sqrt(a)) * 6371.0

def _max_dist_from_source(polygon, src_lat, src_lon):
    if polygon is None or polygon.is_empty:
        return None
    max_d = 0.0
    try:
        for lon, lat in polygon.exterior.coords:
            d = _haversine_km(src_lat, src_lon, lat, lon)
            if d > max_d:
                max_d = d
    except Exception:
        return None
    return max_d if max_d > 0 else None

print("=" * 60)
print("AEGL THREAT ZONE DISTANCES FROM SOURCE")
print("=" * 60)
_ZONE_ORDER = ["AEGL-3", "AEGL-2", "AEGL-1"]
for _zone_name in _ZONE_ORDER:
    _poly   = threat_zones.get(_zone_name)
    _thresh = AEGL_THRESHOLDS.get(_zone_name, "N/A")
    _thresh_str = f"{_thresh:.0f} ppm" if isinstance(_thresh, (int, float)) else str(_thresh)
    _dist_km = _max_dist_from_source(_poly, SOURCE_LAT, SOURCE_LON) if _poly else None
    if _dist_km is not None:
        print(f"  {_zone_name:<8}  threshold: {_thresh_str:<12}  max distance: {_dist_km:.3f} km  ({_dist_km*1000:.0f} m)")
    else:
        print(f"  {_zone_name:<8}  threshold: {_thresh_str:<12}  max distance: -- (no zone formed)")
print()

# ============================================================================
# ANALYTICS CHARTS  (saved as interactive HTML files)
# ============================================================================
print("\nGenerating analytics charts ...")

_analytics_dir = Path(_root) / "outputs" / "threat_zones"
_analytics_dir.mkdir(parents=True, exist_ok=True)
_ts = datetime.now().strftime("%Y%m%d_%H%M%S")

_analytics = [
    ("centerline",  create_centerline_concentration_plot(X, Y, concentration, weather["wind_dir"])),
    ("crosswind",   create_crosswind_concentration_plot(X, Y, concentration)),
    ("contour",     create_concentration_contour_plot(X, Y, concentration, AEGL_THRESHOLDS, weather["wind_dir"])),
    ("statistics",  create_concentration_statistics(concentration, AEGL_THRESHOLDS)),
    ("distance",    create_distance_vs_concentration_plot(X, Y, concentration, AEGL_THRESHOLDS)),
]

_analytics_paths = []
for _name, _fig in _analytics:
    _path = _analytics_dir / f"ammonia_analytics_{_name}_{_ts}.html"
    _fig.write_html(str(_path))
    _analytics_paths.append(_path)
    print(f"  Saved: {_path.name}")

print()

# ============================================================================
# INTERACTIVE THREAT ZONE MAP
# ============================================================================
print("Creating threat zone map ...")
lat_grid, lon_grid = meters_to_latlon(
    X, Y, SOURCE_LAT, SOURCE_LON, weather["wind_dir"],
)
zoom_level, bounds = calculate_optimal_zoom_level(
    lat_grid, lon_grid, concentration,
    threshold=min(AEGL_THRESHOLDS.values()),
)

m = create_dispersion_map(
    source_lat=SOURCE_LAT,
    source_lon=SOURCE_LON,
    x_grid=X,
    y_grid=Y,
    concentration=concentration,
    thresholds=AEGL_THRESHOLDS,
    wind_direction=weather["wind_dir"],
    zoom_start=zoom_level,
    chemical_name=CHEMICAL_NAME,
    source_height=TANK_HEIGHT,
    wind_speed=weather["wind_speed"],
    stability_class=stability_class,
    include_heatmap=True,
    include_compass=True,
)

if resolved_sources:
    m = add_facility_markers(m, resolved_sources) or m

if bounds[0] is not None:
    try:
        m.fit_bounds(
            [[bounds[1], bounds[3]], [bounds[0], bounds[2]]],
            padding=(0.1, 0.1), max_zoom=18,
        )
    except Exception:
        pass

# ============================================================================
# SAVE ALL OUTPUTS & OPEN IN BROWSER
# ============================================================================
_map_path = _analytics_dir / f"ammonia_threat_zones_{_ts}.html"
m.save(str(_map_path))
print(f"Map saved to: {_map_path}")

print("\nOpening all outputs in web browser ...")
webbrowser.open(_map_path.as_uri())
for _p in _analytics_paths:
    webbrowser.open(_p.as_uri())

print("\nDone! All outputs have been opened in your browser.")
print(f"Files are in: {_analytics_dir}")
